var gap = 50;
var chessSet = {}; // 棋盘
var selectedRC = ''; // 以选中的棋子所在行列：1_2
var movedRC = ''; //  吃子或兑子所发生行列: 1_3
var loadedImgs = {}; // 已加载图片
var canvas = null;
var turn = false; // 保证交替执行
var userName = 'lzz';
var rivalName = ''; // 对手
var camp = ''; // a 红, b 绿
var clickCamp = ''; // 当前执行方
var Socket = null;
var app = null;
//var chaseCount = 0; // 如果双方各剩一子，没有办法吃掉对方，相互追逐次数超过5次系统判定为和棋